version: '2.1'
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm run dev < /dev/null & npx jest testing.test.js   
                 
workflows:
  test:
    jobs:
        - build
      # - node/test:
      #     test-results-for: jest
