version: '2.1'
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Server
          command: |
            npm run dev 
          background: true
      - run:
          name: Wait for Server
          command: sleep 5
      - run:
          name: Run Tests
          command: |
            npx jest testing.test.js   
          

      
                 
workflows:
  test:
    jobs:
        - build
