# version: '2.1'
# jobs:
#   build:
#     docker:
#       - image: circleci/node:14
#     steps:
#       - checkout
#       - run:
#           name: Install npm dependencies
#           command: |
#             npm install --save
#       - run:
#           name: Run Server
#           command: |
#             npm run dev 
#           background: true
#       - run:
#           name: Wait for Server
#           command: sleep 5
#       - run:
#           name: Run Tests
#           command: |
#             npm run test   
            
                 
# workflows:
#   test:
#     jobs:
#         - build


version: '2.1'
orbs: 
  node: circleci/node@4.7 
  browser-tools: circleci/browser-tools@1.4.6


jobs:
  api_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Server
          command: |
            npm run dev 
          background: true
      - run:
          name: Wait for Server
          command: sleep 5
      - run:
          name: Run Tests
          command: |
            npm run test:jest 
      - store_artifacts:
          path: API_testing/tests_output
          
  UI_test: 
    docker: 
      - image: cimg/node:lts-browsers 
    steps: 
      - checkout 
      - browser-tools/install-browser-tools 
      - node/install-packages 
      - run:
          command: |
            npm run test:nightwatch 
      - store_artifacts:
          path: UI_automation_testing/tests_output/nightwatch-html-report
                    



# workflows:
#   e2e-test:
#     jobs:
        # - api_test
        # - UI_test